name: Pull Request

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm ci

      # Type checks the library code
      - name: Type check
        run: npm run tscheck

      # Tests the types exported from the library
      - name: Test types
        run: npm run test:types

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build

      - name: Validate build
        run: npm run build:validate-output
